# Minimal Jekyll Configuration for GitHub Pages
# Optimized for serving React app with static assets

# Site settings
title: "Recipe App"
description: "A personal recipe organizer website built with React and Vite"
baseurl: ""
url: ""

# Exclude everything except what we need
exclude:
  - node_modules
  - recipe-app
  - dist
  - "*.log"
  - "*.tmp"
  - ".DS_Store"
  - "Thumbs.db"

# Include only necessary files
include:
  - "index.html"
  - "404.html"
  - "assets/"
  - "docs/"
  - "vite.svg"

# Disable Jekyll processing for static assets
keep_files:
  - assets/
  - vite.svg

# Minimal plugins
plugins:
  - jekyll-github-metadata
