# Minimal Jekyll Configuration for GitHub Pages
# Optimized for serving React app with static assets

# Site settings
title: "Recipe App"
description: "A personal recipe organizer website built with React and Vite"
baseurl: ""
url: ""

# Disable Jekyll processing entirely for static site
exclude:
  - node_modules
  - recipe-app
  - dist
  - "*.log"
  - "*.tmp"
  - ".DS_Store"
  - "Thumbs.db"
  - "*.md"
  - "docs/"

# Include all files in root
include:
  - "index.html"
  - "404.html"
  - "assets/"
  - "vite.svg"
  - ".nojekyll"

# Disable Jekyll processing for static assets
keep_files:
  - assets/
  - vite.svg
  - ".nojekyll"

# Disable Jekyll entirely
plugins: []
